# Generated by Django 4.0 on 2022-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('transcript', models.CharField(blank=True, max_length=30)),
                ('ru_translate', models.CharField(max_length=30)),
                ('dictionaries', models.ManyToManyField(related_name='words', to='dictionary.Dictionary')),
            ],
        ),
    ]
