# Generated by Django 4.0 on 2022-12-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dictionary',
            table='dictionary',
        ),
        migrations.AlterModelTable(
            name='word',
            table='word',
        ),
    ]
