# Generated by Django 4.0 on 2022-12-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_dictionary_table_alter_word_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='dictionaries',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='words',
            field=models.ManyToManyField(related_name='dictionaries', to='dictionary.Word'),
        ),
    ]
