# Generated by Django 4.0 on 2023-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_alter_tokenemail_table_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TokenEmail',
        ),
    ]
